[Theme]
Current=vantaos
CursorTheme=breeze_cursors
Font=Inter,10,-1,5,50,0,0,0,0,0

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
SessionDir=/usr/share/wayland-sessions

[X11]
SessionDir=/usr/share/xsessions
